from app.api.routes import (
    alerts,
    audit,
    auth,
    dashboards,
    detection_rules,
    health,
    incidents,
    ingest,
    iocs,
    log_sources,
    logs,
    reports,
    settings,
    tenants,
    users,
)

routers = [
    auth.router,
    users.router,
    tenants.router,
    ingest.router,
    logs.router,
    log_sources.router,
    detection_rules.router,
    alerts.router,
    incidents.router,
    reports.router,
    audit.router,
    iocs.router,
    dashboards.router,
    health.router,
    settings.router,
]
