[SERVICE]
    Flush        5
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/log/demo.log
    Tag          demo.app
    Read_from_Head true

[FILTER]
    Name         modify
    Match        demo.app
    Add          source_type application
    Add          source_name fluent-bit-demo
    Add          hostname fluentbit-local
    Add          severity informational

[OUTPUT]
    Name         http
    Match        demo.app
    Host         backend
    Port         8000
    URI          /api/ingest/logs
    Format       json
    Header       X-API-Key siem_demo_ingest_key_change_me
    Header       Content-Type application/json
